image: "archlinux:latest"

before_script:
  - pacman -Syy --noconfirm rustup git sdl2 sdl2_image wget cmake base-devel
  - rustup default nightly
  - wget https://zdoom.org/files/fmod/fmodapi44464linux.tar.gz
  - tar -xf fmodapi44464linux.tar.gz && rm fmodapi44464linux.tar.gz
  - mkdir -p /usr/lib /usr/include/fmodex
  - cp -d fmodapi44464linux/api/lib/* /usr/lib/
  - ln -sf /usr/lib/libfmodex64-4.44.64.so /usr/lib/libfmodex-4.44.64.so && ln -sf /usr/lib/libfmodexL64-4.44.64.so /usr/lib/libfmodexL-4.44.64.so



compile_debug:
  script:
    - cargo build

compile_release:
  script:
    - cargo build --release

test:
  script:
    - cargo test
