[workspace]
members = [
    "app/game",
    "app/desktop",
    "app/android",

    "components/audio_engine",
    "components/graphics_engine",
    "components/assets_pipeline",
    "components/event_pipeline",
    "components/imgui_debug_utils"
]
