[package]
name = "audio_engine"
version = "0.1.0"
authors = ["mempler"]
edition = "2018"

[dependencies]
fmod = { version = "0.10.1", optional = true }

[features]
audio_fmod   = [ "fmod" ]

default = [ "audio_fmod" ]